name: Deploy Sanity
on:
  push:
    branches: [main]
jobs:
  sanity-deploy:
    runs-on: ubuntu-22.04
    name: Deploy Sanity
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: yarn install
      - name: deploy-studio
        uses: sanity-io/github-action-sanity@v0.4
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
        with:
          args: . deploy
      - name: deploy-graphql
        run: yarn deploy-graphql:production
